In [1]:
import pandas as pd

df = pd.read_csv("rentfaster_data.csv")
df.head()

,Unnamed: 0,Air Conditioning,Alarm,Balcony,Bike Paths,Bike room,Bus,Cable,Carpeted Floors,Central Vac,...,listing_url,lon,name,price,sq_feet,sublisting,timestamp,type,unit_name,unit_notes
0,NaN,1.0,NaN,1.0,1.0,1.0,1.0,NaN,NaN,NaN,...,https://www.rentfaster.ca/343046,-114.065254,Suite 4,$1775.00,1024,4,2020-03-29 14:02:07.197616,Apartment,NaN,Two Bedroom
1,NaN,1.0,NaN,1.0,1.0,1.0,1.0,NaN,1.0,NaN,...,https://www.rentfaster.ca/321318,-114.066229,Suite 0,$1950.00,943,0,2020-03-29 14:03:07.714689,Condo,NaN,NaN
2,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,NaN,NaN,...,https://www.rentfaster.ca/406139,-114.103649,Suite 0,$1800.00,850,0,2020-03-29 14:04:08.349238,Condo,NaN,NaN
3,NaN,NaN,NaN,1.0,1.0,NaN,1.0,NaN,1.0,NaN,...,https://www.rentfaster.ca/406142,-114.089811,Suite 0,$1850.00,1100,0,2020-03-29 14:05:08.902662,Condo,NaN,NaN
4,NaN,1.0,NaN,1.0,1.0,NaN,1.0,NaN,1.0,NaN,...,https://www.rentfaster.ca/405938,-114.078619,Suite 0,$2100.00,1050,0,2020-03-29 14:17:18.149423,Apartment,NaN,NaN

In [2]:
import googlemaps
import configparser

config = configparser.ConfigParser()
config.read("secrets/config.ini")
API_key = config['Keys']['google_API']
gmaps = googlemaps.Client(key=API_key)

In [3]:
import time
import datetime

critical_address_gps = {'cole_home': {'gps':[51.1191706,-114.2229905], 'mode': 'transit', 'departure_time':datetime.datetime(2020,4,25,17)},
                       'tiff_home': {'gps': [50.9751225,-114.0240217], 'mode': 'driving', 'departure_time':datetime.datetime(2020,4,25,17)},
                       'acadia_clinic': {'gps': [50.9602494,-114.0471263,17], 'mode': 'driving', 'departure_time':datetime.datetime(2020,4,27,8)},
                       'wildlife': {'gps': [51.1575318,-114.2178905], 'mode': 'driving', 'departure_time':datetime.datetime(2020,4,30,8)}
                       }

def extract_travel_times(directions):
    travel_times = {}
    for s in directions[0]['legs'][0]['steps']:
        if s['travel_mode'] in travel_times.keys():
            travel_times[s['travel_mode']] = travel_times[s['travel_mode']] + s['duration']['value']
        else:
            travel_times[s['travel_mode']] = s['duration']['value']
    return travel_times

def get_critical_travel_times(df, critical_address_gps):
    data = {}
    for i, rw in df.iterrows():
        time.sleep(1)
        for a, d_config in critical_address_gps.items():
            directs = gmaps.directions(origin = [rw['lat'], rw['lon']],
                                       destination = d_config['gps'], mode = d_config['mode'],
                                       departure_time = d_config['departure_time'],
                                       alternatives = False)
            
            times = extract_travel_times(directs)
            for mode, t_val in times.items():
                data_col = f'{a}_{mode}'
                if data_col in data.keys():
                    data[data_col].append(t_val)
                else:
                    data[data_col] = [t_val]
    time_df = pd.DataFrame(data)
    return pd.concat([df,time_df], axis = 1)

In [4]:
tst = get_critical_travel_times(df, critical_address_gps)

In [5]:
tst.head()

,Unnamed: 0,Air Conditioning,Alarm,Balcony,Bike Paths,Bike room,Bus,Cable,Carpeted Floors,Central Vac,...,sublisting,timestamp,type,unit_name,unit_notes,cole_home_WALKING,cole_home_TRANSIT,tiff_home_DRIVING,acadia_clinic_DRIVING,wildlife_DRIVING
0,NaN,1.0,NaN,1.0,1.0,1.0,1.0,NaN,NaN,NaN,...,4,2020-03-29 14:02:07.197616,Apartment,NaN,Two Bedroom,923,2160,883,935,1799
1,NaN,1.0,NaN,1.0,1.0,1.0,1.0,NaN,1.0,NaN,...,0,2020-03-29 14:03:07.714689,Condo,NaN,NaN,1862,1500,954,1006,1597
2,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,NaN,NaN,...,0,2020-03-29 14:04:08.349238,Condo,NaN,NaN,1660,2220,939,1099,1474
3,NaN,NaN,NaN,1.0,1.0,NaN,1.0,NaN,1.0,NaN,...,0,2020-03-29 14:05:08.902662,Condo,NaN,NaN,1719,1440,1022,1190,1414
4,NaN,1.0,NaN,1.0,1.0,NaN,1.0,NaN,1.0,NaN,...,0,2020-03-29 14:17:18.149423,Apartment,NaN,NaN,2095,1260,1093,1145,1420